version: "3.1"


services:
  jenkins:
    build: ./Jenkins
    restart: on-failure:3
    volumes:
      - ~/jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
  mysql:
    build: ./MySQL
    ports:
      - "3306:3006"
    restart: on-failure:3
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=sonarqq
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
  sonarqube:
    build: ./SonarQube
    restart: on-failure:3
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=root 
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql/sonarqq?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
  gitlab:
    build: ./GitLab
    restart: on-failure:3
    ports:
      - "10022:22"
      - "10080:80"
    environment:
      - GITLAB_PORT= 10080
      - GITLAB_SSH_PORT= 10022
      - DB_NAME= sonarqq
      - DB_USER = root
      - DB_PASS= root
